// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetAmb.Data;

#nullable disable

namespace VetAmb.Migrations
{
    [DbContext(typeof(VetAmbDbContext))]
    [Migration("20260611125137_AddUniqueIndexesForOibAndJmbg")]
    partial class AddUniqueIndexesForOibAndJmbg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VetAmb.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("JMBG")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OIB")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VetAmb.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RescheduleReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("VetId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDateTime = new DateTime(2026, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Sve u redu, vitalni znakovi uredni",
                            PatientId = 1,
                            Reason = "Godišnji pregled",
                            Status = 2,
                            VetId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDateTime = new DateTime(2026, 5, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Zahvat uspješan, oporavak teče uredno",
                            PatientId = 3,
                            Reason = "Uklanjanje lipoma",
                            Status = 2,
                            VetId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDateTime = new DateTime(2026, 5, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Zdrava, bez promjena",
                            PatientId = 4,
                            Reason = "Rutinski pregled",
                            Status = 2,
                            VetId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDateTime = new DateTime(2026, 4, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Zubni kamenac uklonjen, preporučuje se kontrola za 6 mj.",
                            PatientId = 7,
                            Reason = "Problemi sa zubima",
                            Status = 2,
                            VetId = 6
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDateTime = new DateTime(2026, 5, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Odgođeno na 12. svibnja 2026. – 15:00",
                            PatientId = 9,
                            Reason = "Bol u nozi",
                            RescheduleReason = "Vlasnik nedostupan zbog puta",
                            Status = 5,
                            VetId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDateTime = new DateTime(2026, 5, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Zahvat obavljen bez komplikacija",
                            PatientId = 2,
                            Reason = "Čišćenje zubi",
                            Status = 2,
                            VetId = 1
                        });
                });

            modelBuilder.Entity("VetAmb.Models.AppointmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("AppointmentId", "ServiceId")
                        .IsUnique();

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 4,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 4,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 5,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 6,
                            ServiceId = 4
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 42, Zagreb",
                            Email = "info@vetklinika.hr",
                            FoundationDate = new DateTime(2010, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxCapacity = 50,
                            Name = "Paws & Claws Vet",
                            Phone = "01 234 5678",
                            RegistrationNumber = "CLN-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Varšavska 15, Zagreb",
                            Email = "kontakt@vetambulanta.hr",
                            FoundationDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxCapacity = 30,
                            Name = "Happy Tails Clinic",
                            Phone = "01 345 6789",
                            RegistrationNumber = "CLN-002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Marmontova 3, Split",
                            Email = "info@vetcentar-split.hr",
                            FoundationDate = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxCapacity = 40,
                            Name = "VetCare Plus",
                            Phone = "021 456 7890",
                            RegistrationNumber = "CLN-003"
                        });
                });

            modelBuilder.Entity("VetAmb.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnosis = "Zdrav pacijent – rutinski pregled",
                            Notes = "Godišnji pregled – svi vitalni znakovi uredni",
                            PatientId = 1,
                            RecordDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Nije potrebno liječenje"
                        },
                        new
                        {
                            Id = 2,
                            Diagnosis = "Lipom (benigna tvorba)",
                            Notes = "Postoperativni oporavak teče uredno",
                            PatientId = 3,
                            RecordDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Kirurško uklanjanje"
                        },
                        new
                        {
                            Id = 3,
                            Diagnosis = "Zdrav pacijent – rutinski pregled",
                            Notes = "Tjelesna masa stabilna",
                            PatientId = 4,
                            RecordDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Nije potrebno liječenje"
                        },
                        new
                        {
                            Id = 4,
                            Diagnosis = "Parodontna bolest stupanj 2",
                            Notes = "Kontrola za 6 mjeseci",
                            PatientId = 7,
                            RecordDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Profesionalno čišćenje zubi"
                        },
                        new
                        {
                            Id = 5,
                            Diagnosis = "Nakupljanje zubnog kamenca",
                            Notes = "Problem riješen",
                            PatientId = 2,
                            RecordDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Čišćenje zubi"
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 10, Zagreb",
                            ClinicId = 1,
                            Email = "ivan.horvat@gmail.com",
                            FirstName = "Ivan",
                            IdNumber = "OWN-001",
                            LastName = "Horvat",
                            Phone = "091 234 5678",
                            RegistrationDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Maksimirska 22, Zagreb",
                            ClinicId = 1,
                            Email = "petra.babic@gmail.com",
                            FirstName = "Petra",
                            IdNumber = "OWN-002",
                            LastName = "Babić",
                            Phone = "098 765 4321",
                            RegistrationDate = new DateTime(2021, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gajeva 5, Zagreb",
                            ClinicId = 2,
                            Email = "tomislav.knezevic@gmail.com",
                            FirstName = "Tomislav",
                            IdNumber = "OWN-003",
                            LastName = "Knežević",
                            Phone = "095 111 2233",
                            RegistrationDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Šubićeva 8, Zagreb",
                            ClinicId = 2,
                            Email = "sara.petrovic@gmail.com",
                            FirstName = "Sara",
                            IdNumber = "OWN-004",
                            LastName = "Petrović",
                            Phone = "099 876 5432",
                            RegistrationDate = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Marmontova 3, Split",
                            ClinicId = 3,
                            Email = "nina.vukovic@gmail.com",
                            FirstName = "Nina",
                            IdNumber = "OWN-005",
                            LastName = "Vuković",
                            Phone = "091 500 6001",
                            RegistrationDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Obala 17, Split",
                            ClinicId = 3,
                            Email = "filip.radic@gmail.com",
                            FirstName = "Filip",
                            IdNumber = "OWN-006",
                            LastName = "Radić",
                            Phone = "098 600 1700",
                            RegistrationDate = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MicrochipId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Njemački ovčar",
                            Color = "Crno-smeđa",
                            DateOfBirth = new DateTime(2018, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0001",
                            Name = "Rex",
                            OwnerId = 1,
                            Species = 0,
                            Weight = 32.5m
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Sijamska",
                            Color = "Kremasta",
                            DateOfBirth = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0002",
                            Name = "Mici",
                            OwnerId = 1,
                            Species = 1,
                            Weight = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Labrador retriver",
                            Color = "Zlatna",
                            DateOfBirth = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0003",
                            Name = "Bruno",
                            OwnerId = 2,
                            Species = 0,
                            Weight = 28.0m
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Perzijska",
                            Color = "Bijela",
                            DateOfBirth = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0004",
                            Name = "Luna",
                            OwnerId = 3,
                            Species = 1,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Kakadu",
                            Color = "Žuta",
                            DateOfBirth = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0005",
                            Name = "Kiki",
                            OwnerId = 3,
                            Species = 2,
                            Weight = 0.1m
                        },
                        new
                        {
                            Id = 6,
                            Breed = "Patuljasti kunić",
                            Color = "Smeđa",
                            DateOfBirth = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0006",
                            Name = "Šarko",
                            OwnerId = 4,
                            Species = 3,
                            Weight = 1.8m
                        },
                        new
                        {
                            Id = 7,
                            Breed = "Pudl",
                            Color = "Bijela",
                            DateOfBirth = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0007",
                            Name = "Pahuljica",
                            OwnerId = 5,
                            Species = 0,
                            Weight = 7.5m
                        },
                        new
                        {
                            Id = 8,
                            Breed = "Sirijski hrčak",
                            Color = "Narančasta",
                            DateOfBirth = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0008",
                            Name = "Hrčko",
                            OwnerId = 5,
                            Species = 4,
                            Weight = 0.15m
                        },
                        new
                        {
                            Id = 9,
                            Breed = "Maine Coon",
                            Color = "Tigrasta",
                            DateOfBirth = new DateTime(2019, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0009",
                            Name = "Zara",
                            OwnerId = 6,
                            Species = 1,
                            Weight = 6.3m
                        });
                });

            modelBuilder.Entity("VetAmb.Models.PatientAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAttachments");
                });

            modelBuilder.Entity("VetAmb.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rutinski zdravstveni pregled životinje",
                            EstimatedDurationMinutes = 30,
                            Name = "Opći pregled",
                            Price = 30m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standardno cijepljenje prema protokolu",
                            EstimatedDurationMinutes = 15,
                            Name = "Cijepljenje",
                            Price = 25m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Manja kirurška intervencija",
                            EstimatedDurationMinutes = 60,
                            Name = "Manji kirurški zahvat",
                            Price = 150m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Profesionalno čišćenje zubnog kamenca",
                            EstimatedDurationMinutes = 45,
                            Name = "Čišćenje zubi",
                            Price = 80m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Dijagnostičko slikanje rentgenom",
                            EstimatedDurationMinutes = 20,
                            Name = "Rendgensko snimanje",
                            Price = 60m
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Vets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            FirstName = "Ana",
                            HourlyRate = 80m,
                            LastName = "Kovač",
                            LicenseNumber = "VET-101",
                            Phone = "091 234 1001",
                            Specialization = 0,
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            FirstName = "Marko",
                            HourlyRate = 100m,
                            LastName = "Novak",
                            LicenseNumber = "VET-102",
                            Phone = "092 456 1002",
                            Specialization = 1,
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            FirstName = "Luka",
                            HourlyRate = 120m,
                            LastName = "Jurić",
                            LicenseNumber = "VET-201",
                            Phone = "095 678 3001",
                            Specialization = 3,
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            FirstName = "Maja",
                            HourlyRate = 90m,
                            LastName = "Tomić",
                            LicenseNumber = "VET-202",
                            Phone = "099 321 3002",
                            Specialization = 4,
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 5,
                            ClinicId = 3,
                            FirstName = "Elena",
                            HourlyRate = 130m,
                            LastName = "Matić",
                            LicenseNumber = "VET-301",
                            Phone = "098 123 5001",
                            Specialization = 5,
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            ClinicId = 3,
                            FirstName = "Dario",
                            HourlyRate = 95m,
                            LastName = "Šimić",
                            LicenseNumber = "VET-302",
                            Phone = "091 765 5002",
                            Specialization = 2,
                            YearsOfExperience = 8
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VetAmb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VetAmb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetAmb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VetAmb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetAmb.Models.Appointment", b =>
                {
                    b.HasOne("VetAmb.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetAmb.Models.Vet", "Vet")
                        .WithMany("Appointments")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("VetAmb.Models.AppointmentService", b =>
                {
                    b.HasOne("VetAmb.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetAmb.Models.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("VetAmb.Models.MedicalRecord", b =>
                {
                    b.HasOne("VetAmb.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VetAmb.Models.Owner", b =>
                {
                    b.HasOne("VetAmb.Models.Clinic", "Clinic")
                        .WithMany("Owners")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("VetAmb.Models.Patient", b =>
                {
                    b.HasOne("VetAmb.Models.Owner", "Owner")
                        .WithMany("Patients")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VetAmb.Models.PatientAttachment", b =>
                {
                    b.HasOne("VetAmb.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VetAmb.Models.Vet", b =>
                {
                    b.HasOne("VetAmb.Models.Clinic", "Clinic")
                        .WithMany("Vets")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("VetAmb.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("VetAmb.Models.Clinic", b =>
                {
                    b.Navigation("Owners");

                    b.Navigation("Vets");
                });

            modelBuilder.Entity("VetAmb.Models.Owner", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("VetAmb.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("VetAmb.Models.Service", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("VetAmb.Models.Vet", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
