// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetAmb.Data;

#nullable disable

namespace VetAmb.Migrations
{
    [DbContext(typeof(VetAmbDbContext))]
    [Migration("20260521104413_RemoveServiceIdFromAppointment")]
    partial class RemoveServiceIdFromAppointment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VetAmb.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RescheduleReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("VetId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDateTime = new DateTime(2026, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "All good",
                            PatientId = 1,
                            Reason = "Annual checkup",
                            Status = 2,
                            VetId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDateTime = new DateTime(2026, 5, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Successful",
                            PatientId = 3,
                            Reason = "Lump removal",
                            Status = 2,
                            VetId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDateTime = new DateTime(2026, 5, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Healthy",
                            PatientId = 4,
                            Reason = "Routine visit",
                            Status = 2,
                            VetId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDateTime = new DateTime(2026, 4, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Treated",
                            PatientId = 7,
                            Reason = "Dental issues",
                            Status = 2,
                            VetId = 6
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDateTime = new DateTime(2026, 5, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Rescheduled to May 12, 2026 - 15:00",
                            PatientId = 9,
                            Reason = "Leg pain",
                            RescheduleReason = "Owner unavailable due to travel",
                            Status = 5,
                            VetId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDateTime = new DateTime(2026, 5, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Done",
                            PatientId = 2,
                            Reason = "Teeth cleaning",
                            Status = 2,
                            VetId = 1
                        });
                });

            modelBuilder.Entity("VetAmb.Models.AppointmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("AppointmentId", "ServiceId")
                        .IsUnique();

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 4,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 4,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 5,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 6,
                            ServiceId = 4
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Email = "info@pawsclaws.com",
                            FoundationDate = new DateTime(2010, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxCapacity = 50,
                            Name = "Paws & Claws Vet",
                            Phone = "555-1000",
                            RegistrationNumber = "CLN-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Park Rd",
                            Email = "contact@happytails.com",
                            FoundationDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxCapacity = 30,
                            Name = "Happy Tails Clinic",
                            Phone = "555-3000",
                            RegistrationNumber = "CLN-002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 River Blvd",
                            Email = "hello@vetcareplus.com",
                            FoundationDate = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxCapacity = 40,
                            Name = "VetCare Plus",
                            Phone = "555-5000",
                            RegistrationNumber = "CLN-003"
                        });
                });

            modelBuilder.Entity("VetAmb.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnosis = "Healthy - routine exam",
                            Notes = "Annual visit - all vitals normal",
                            PatientId = 1,
                            RecordDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "None required"
                        },
                        new
                        {
                            Id = 2,
                            Diagnosis = "Lipoma (benign lump)",
                            Notes = "Post-op recovery good",
                            PatientId = 3,
                            RecordDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Surgical removal"
                        },
                        new
                        {
                            Id = 3,
                            Diagnosis = "Healthy - routine exam",
                            Notes = "Weight stable",
                            PatientId = 4,
                            RecordDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "None required"
                        },
                        new
                        {
                            Id = 4,
                            Diagnosis = "Periodontal disease grade 2",
                            Notes = "Follow-up in 6 months",
                            PatientId = 7,
                            RecordDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Professional dental cleaning"
                        },
                        new
                        {
                            Id = 5,
                            Diagnosis = "Dental tartar buildup",
                            Notes = "Resolved",
                            PatientId = 2,
                            RecordDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Treatment = "Teeth cleaning"
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10 Oak Ave",
                            ClinicId = 1,
                            Email = "ivan@mail.com",
                            FirstName = "Ivan",
                            IdNumber = "OWN-001",
                            LastName = "Horvat",
                            Phone = "555-2001",
                            RegistrationDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Elm St",
                            ClinicId = 1,
                            Email = "petra@mail.com",
                            FirstName = "Petra",
                            IdNumber = "OWN-002",
                            LastName = "Babić",
                            Phone = "555-2002",
                            RegistrationDate = new DateTime(2021, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 Pine Ln",
                            ClinicId = 2,
                            Email = "tomi@mail.com",
                            FirstName = "Tomislav",
                            IdNumber = "OWN-003",
                            LastName = "Knežević",
                            Phone = "555-4001",
                            RegistrationDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "8 Birch Dr",
                            ClinicId = 2,
                            Email = "sara@mail.com",
                            FirstName = "Sara",
                            IdNumber = "OWN-004",
                            LastName = "Petrović",
                            Phone = "555-4002",
                            RegistrationDate = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "3 Cedar Ct",
                            ClinicId = 3,
                            Email = "nina@mail.com",
                            FirstName = "Nina",
                            IdNumber = "OWN-005",
                            LastName = "Vuković",
                            Phone = "555-6001",
                            RegistrationDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "17 Maple Way",
                            ClinicId = 3,
                            Email = "filip@mail.com",
                            FirstName = "Filip",
                            IdNumber = "OWN-006",
                            LastName = "Radić",
                            Phone = "555-6002",
                            RegistrationDate = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MicrochipId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "German Shepherd",
                            Color = "Black/Tan",
                            DateOfBirth = new DateTime(2018, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0001",
                            Name = "Rex",
                            OwnerId = 1,
                            Species = 0,
                            Weight = 32.5m
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Siamese",
                            Color = "Cream",
                            DateOfBirth = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0002",
                            Name = "Mici",
                            OwnerId = 1,
                            Species = 1,
                            Weight = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Labrador",
                            Color = "Golden",
                            DateOfBirth = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0003",
                            Name = "Buddy",
                            OwnerId = 2,
                            Species = 0,
                            Weight = 28.0m
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Persian",
                            Color = "White",
                            DateOfBirth = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0004",
                            Name = "Luna",
                            OwnerId = 3,
                            Species = 1,
                            Weight = 5.0m
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Cockatiel",
                            Color = "Yellow",
                            DateOfBirth = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0005",
                            Name = "Kiki",
                            OwnerId = 3,
                            Species = 2,
                            Weight = 0.1m
                        },
                        new
                        {
                            Id = 6,
                            Breed = "Holland Lop",
                            Color = "Brown",
                            DateOfBirth = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0006",
                            Name = "Rocky",
                            OwnerId = 4,
                            Species = 3,
                            Weight = 1.8m
                        },
                        new
                        {
                            Id = 7,
                            Breed = "Poodle",
                            Color = "White",
                            DateOfBirth = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0007",
                            Name = "Max",
                            OwnerId = 5,
                            Species = 0,
                            Weight = 7.5m
                        },
                        new
                        {
                            Id = 8,
                            Breed = "Syrian",
                            Color = "Orange",
                            DateOfBirth = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0008",
                            Name = "Coco",
                            OwnerId = 5,
                            Species = 4,
                            Weight = 0.15m
                        },
                        new
                        {
                            Id = 9,
                            Breed = "Maine Coon",
                            Color = "Tabby",
                            DateOfBirth = new DateTime(2019, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MicrochipId = "MC-0009",
                            Name = "Zara",
                            OwnerId = 6,
                            Species = 1,
                            Weight = 6.3m
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Routine health examination",
                            EstimatedDurationMinutes = 30,
                            Name = "General Checkup",
                            Price = 30m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard vaccination",
                            EstimatedDurationMinutes = 15,
                            Name = "Vaccination",
                            Price = 25m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Minor surgical procedure",
                            EstimatedDurationMinutes = 60,
                            Name = "Minor Surgery",
                            Price = 150m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Professional teeth cleaning",
                            EstimatedDurationMinutes = 45,
                            Name = "Dental Cleaning",
                            Price = 80m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Diagnostic imaging",
                            EstimatedDurationMinutes = 20,
                            Name = "X-Ray",
                            Price = 60m
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Vets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            FirstName = "Ana",
                            HourlyRate = 80m,
                            LastName = "Kovač",
                            LicenseNumber = "VET-101",
                            Phone = "555-1001",
                            Specialization = 0,
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            FirstName = "Marko",
                            HourlyRate = 100m,
                            LastName = "Novak",
                            LicenseNumber = "VET-102",
                            Phone = "555-1002",
                            Specialization = 1,
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            FirstName = "Luka",
                            HourlyRate = 120m,
                            LastName = "Jurić",
                            LicenseNumber = "VET-201",
                            Phone = "555-3001",
                            Specialization = 3,
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            FirstName = "Maja",
                            HourlyRate = 90m,
                            LastName = "Tomić",
                            LicenseNumber = "VET-202",
                            Phone = "555-3002",
                            Specialization = 4,
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 5,
                            ClinicId = 3,
                            FirstName = "Elena",
                            HourlyRate = 130m,
                            LastName = "Matić",
                            LicenseNumber = "VET-301",
                            Phone = "555-5001",
                            Specialization = 5,
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            ClinicId = 3,
                            FirstName = "Dario",
                            HourlyRate = 95m,
                            LastName = "Šimić",
                            LicenseNumber = "VET-302",
                            Phone = "555-5002",
                            Specialization = 2,
                            YearsOfExperience = 8
                        });
                });

            modelBuilder.Entity("VetAmb.Models.Appointment", b =>
                {
                    b.HasOne("VetAmb.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetAmb.Models.Vet", "Vet")
                        .WithMany("Appointments")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("VetAmb.Models.AppointmentService", b =>
                {
                    b.HasOne("VetAmb.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetAmb.Models.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("VetAmb.Models.MedicalRecord", b =>
                {
                    b.HasOne("VetAmb.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VetAmb.Models.Owner", b =>
                {
                    b.HasOne("VetAmb.Models.Clinic", "Clinic")
                        .WithMany("Owners")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("VetAmb.Models.Patient", b =>
                {
                    b.HasOne("VetAmb.Models.Owner", "Owner")
                        .WithMany("Patients")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VetAmb.Models.Vet", b =>
                {
                    b.HasOne("VetAmb.Models.Clinic", "Clinic")
                        .WithMany("Vets")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("VetAmb.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("VetAmb.Models.Clinic", b =>
                {
                    b.Navigation("Owners");

                    b.Navigation("Vets");
                });

            modelBuilder.Entity("VetAmb.Models.Owner", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("VetAmb.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("VetAmb.Models.Service", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("VetAmb.Models.Vet", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
